# Generated by Django 6.0.6 on 2026-06-10 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. AIMS Senegal Thesis Defense 2024', max_length=200)),
                ('number_of_years', models.IntegerField(default=1)),
                ('program', models.CharField(default='Cooperative Masters', max_length=200)),
                ('academic_year', models.CharField(default='2024-2026', max_length=20)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='excel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='aimssn', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Password',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=20)),
                ('surname', models.CharField(max_length=100)),
                ('given_names', models.CharField(max_length=200)),
                ('thesis_title', models.TextField()),
                ('room', models.IntegerField(choices=[(1, 'AIMS Room 1'), (2, 'AIMS Room 2')], default=1)),
                ('defense_date', models.DateField(blank=True, null=True)),
                ('supervisor_1_name', models.CharField(blank=True, max_length=200)),
                ('supervisor_1_email', models.CharField(blank=True, max_length=200)),
                ('supervisor_1_institution', models.CharField(blank=True, max_length=200)),
                ('supervisor_2_name', models.CharField(blank=True, max_length=200)),
                ('supervisor_2_email', models.CharField(blank=True, max_length=200)),
                ('jury_president_name', models.CharField(blank=True, max_length=200)),
                ('jury_president_email', models.CharField(blank=True, max_length=200)),
                ('jury_president_affiliation', models.CharField(blank=True, max_length=200)),
                ('examiner_1_name', models.CharField(blank=True, max_length=200)),
                ('examiner_1_email', models.CharField(blank=True, max_length=200)),
                ('examiner_1_affiliation', models.CharField(blank=True, max_length=200)),
                ('examiner_2_name', models.CharField(blank=True, max_length=200)),
                ('examiner_2_email', models.CharField(blank=True, max_length=200)),
                ('examiner_2_affiliation', models.CharField(blank=True, max_length=200)),
                ('examiner_3_name', models.CharField(blank=True, max_length=200)),
                ('examiner_3_email', models.CharField(blank=True, max_length=200)),
                ('examiner_3_affiliation', models.CharField(blank=True, max_length=200)),
                ('defense_status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_link_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='defense.session')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_email', models.EmailField(max_length=254)),
                ('evaluator_name', models.CharField(max_length=200)),
                ('student_full_name', models.CharField(max_length=200)),
                ('thesis_title_confirmed', models.TextField()),
                ('role', models.CharField(choices=[('supervisor', 'Supervisor'), ('examiner', 'Examiner'), ('president', 'Jury President')], max_length=20)),
                ('research_paper', models.BooleanField(default=False)),
                ('score_clarity', models.IntegerField(default=0)),
                ('score_literature', models.IntegerField(default=0)),
                ('score_knowledge', models.IntegerField(default=0)),
                ('score_critical', models.IntegerField(default=0)),
                ('score_presentation', models.IntegerField(default=0)),
                ('additional_info', models.TextField(blank=True)),
                ('annotated_document', models.FileField(blank=True, null=True, upload_to='pv_uploads/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='defense.student')),
            ],
        ),
    ]
