# Generated by Django 6.0.6 on 2026-06-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='started_by_session',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
