# Generated by Django 6.0.6 on 2026-06-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0003_seed_site_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(default='Dr. Coura Balde', help_text="Full name shown in the signature block, e.g. 'Dr. Coura Balde'", max_length=200)),
                ('director_title', models.CharField(default='Academic Manager, AIMS Senegal', help_text="Title/role shown under the name, e.g. 'Academic Manager, AIMS Senegal'", max_length=200)),
                ('institution_name', models.CharField(default='AIMS Senegal', help_text='Institution name (used for reference, not always printed)', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Logo shown in the PV header. If empty, the default AIMS logo is used.', null=True, upload_to='pv_settings/')),
            ],
            options={
                'verbose_name': 'PV Settings',
                'verbose_name_plural': 'PV Settings',
            },
        ),
    ]
